version: '2'
services :
  web :
    build : .
    links :
      - db
    ports :
      - 80:80
      - 443:443
    volumes :
      - ./www:/var/www/html
  db :
    image : mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : otrs
      MYSQL_PASSWORD : otrs
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sql/mysqlconf/my.cnf:/etc/mysql/my.cnf
    ports :
      - 3306:3306
